create extension if not exists pgcrypto;

create table if not exists public.phosphoros_cases (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  theme text not null default 'sexual-violence',
  case_label text not null,
  person_label text,
  location text,
  incident_date date,
  incident_date_text text,
  public_date date,
  victim_status text not null,
  suspect_status text not null,
  legal_status text,
  consequence text,
  ecli text,
  summary text,
  evidence_notes text,
  unknowns text,
  source_level text,
  meridian_content_id uuid,
  is_featured boolean not null default false,
  featured_position integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.phosphoros_cases enable row level security;

drop policy if exists "Public can read phosphoros cases" on public.phosphoros_cases;
create policy "Public can read phosphoros cases"
on public.phosphoros_cases
for select
to anon, authenticated
using (true);

insert into public.phosphoros_cases (
  slug,
  theme,
  case_label,
  person_label,
  location,
  incident_date,
  incident_date_text,
  public_date,
  victim_status,
  suspect_status,
  legal_status,
  consequence,
  ecli,
  summary,
  evidence_notes,
  unknowns,
  source_level,
  is_featured,
  featured_position
)
values
(
  'apeldoorn-cold-case-1993',
  'sexual-violence',
  'Apeldoorn · cold case 1993',
  '53-jarige verdachte',
  'Apeldoorn',
  null,
  'augustus 1993',
  '2026-08-20',
  'Aangifte uit 1993; oud DNA-spoor bewaard',
  'Verdachte aangehouden · geen einduitkomst',
  'Onderzoek / verdenking',
  'Nog geen veroordeling, straf of openbare tenlastelegging',
  null,
  'Na ongeveer 33 jaar is voor het eerst een verdachte aangehouden. Politie meldt dat zijn DNA overeenkomt met een oud spoor dat via verwantschapsonderzoek naar hem leidde.',
  'DNA-spoor en DNA-verwantschapsonderzoek vormen de publieke kern van het bewijs.',
  'Nog geen OM-eis, dagvaarding of rechtbankuitspraak openbaar.',
  'primair: politie',
  true,
  1
),
(
  'amsterdam-zorgmedewerker-14-slachtoffers',
  'sexual-violence',
  'Amsterdam · zorgmedewerker',
  'Verdachte zorgmedewerker',
  'Amsterdam',
  null,
  'meldingen april/juni; aangifte november 2025',
  '2026-08-05',
  'Minstens 14 slachtoffers in onderzoek',
  'Vervolging loopt · geen einduitkomst',
  'Vervolging',
  'Nog geen definitieve strafrechtelijke consequentie',
  null,
  'In het onderzoek zijn minstens veertien slachtoffers bekend. De vervolging omvat onder meer poging tot verkrachting van een 2-jarig kind.',
  'Eerdere meldingen bij een andere kinderopvang, ontslag, later een nieuwe aangifte en vervolgens bredere meldingen vormen een belangrijke tijdlijn.',
  'Niet openbaar welke feiten precies per slachtoffer worden vervolgd en hoeveel uiteindelijk bewijsbaar blijken.',
  'secundair: NOS / AT5 / RTL',
  true,
  2
),
(
  'amsterdam-ecli-rbams-2026-7788',
  'sexual-violence',
  'Amsterdam · ECLI:NL:RBAMS:2026:7788',
  'Veroordeelde verdachte',
  'Amsterdam',
  '2024-10-05',
  '5 oktober 2024',
  '2026-08-05',
  'Verklaring betrouwbaar bevonden en ondersteund',
  'Veroordeeld · 36 maanden cel',
  'Veroordeeld',
  '36 maanden gevangenisstraf en €3.000 immateriële schadevergoeding',
  'ECLI:NL:RBAMS:2026:7788',
  'De rechtbank vond voldoende steunbewijs voor de kern van de verkrachtingsbeschuldiging.',
  'Verklaring aangeefster, eigen verklaring verdachte over seksuele handelingen, verklaringen van twee anderen en een 112-opname kort na het incident.',
  'Niet alle afzonderlijk beschreven handelingen zijn bewezen.',
  'primair: Rechtspraak',
  true,
  3
),
(
  'roermond-afterparty-2025',
  'sexual-violence',
  'Roermond · afterparty',
  'Vrijgesproken verdachte',
  'Roermond',
  null,
  'juni 2025',
  '2026-08-03',
  'Aangifte; gebrek aan instemming niet voldoende bewezen',
  'Vrijgesproken',
  'Vrijspraak',
  'Geen strafrechtelijke consequentie voor verkrachting',
  'ECLI:NL:RBLIM:2026:7954',
  'Seksueel contact stond vast; het geschil draaide om instemming. De rechtbank vond onvoldoende bewijs dat gebrek aan instemming juridisch kon worden vastgesteld.',
  'De zaak maakt zichtbaar dat bewijs van seksuele handelingen niet hetzelfde is als bewijs over instemming.',
  'Vrijspraak stelt niet vast dat de aangifte bewust onwaar was.',
  'primair dossier / secundair ontsloten',
  true,
  4
),
(
  'rotterdam-zuiderpark-7-jarig-meisje',
  'sexual-violence',
  'Rotterdam · Zuiderpark',
  'Veroordeelde verdachte',
  'Rotterdam',
  null,
  'incidentdatum niet in dit overzicht gespecificeerd',
  '2026-07-28',
  'Verkrachting en aanranding van 7-jarig meisje bewezen',
  'Veroordeeld · 2 jaar cel + tbs',
  'Veroordeeld',
  '2 jaar gevangenisstraf en tbs met dwangverpleging',
  null,
  'DNA speelde een grote rol. Een oud zedenfeit uit 2011 kwam eveneens naar voren maar kon als zedenfeit door verjaring niet meer worden vervolgd.',
  'DNA, NFI-onderzoek, camerabeelden, getuigen en telefoongegevens worden in het publieke dossier genoemd.',
  'Afzonderlijke vrijheidsberovingsverdenkingen leidden tot vrijspraak; het oude zedenfeit illustreert de rol van verjaring.',
  'primair: Rechtspraak / OM',
  true,
  5
)
on conflict (slug) do update set
  theme = excluded.theme,
  case_label = excluded.case_label,
  person_label = excluded.person_label,
  location = excluded.location,
  incident_date = excluded.incident_date,
  incident_date_text = excluded.incident_date_text,
  public_date = excluded.public_date,
  victim_status = excluded.victim_status,
  suspect_status = excluded.suspect_status,
  legal_status = excluded.legal_status,
  consequence = excluded.consequence,
  ecli = excluded.ecli,
  summary = excluded.summary,
  evidence_notes = excluded.evidence_notes,
  unknowns = excluded.unknowns,
  source_level = excluded.source_level,
  is_featured = excluded.is_featured,
  featured_position = excluded.featured_position,
  updated_at = now();